volumes:
  postgres:

services:
  postgres:
    container_name: pick_container_name
    labels:
      org.springframework.boot.service-connection: postgres
    image: "postgres:17"
    environment:
      POSTGRES_USER: "pick_user_name"
      POSTGRES_PASSWORD: "pick_the_pass"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
      - ./db/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped
